# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-OpenID-Consumer-Yadis
version:      0.01
version_from: lib/Net/OpenID/Consumer/Yadis.pm
installdirs:  site
requires:
    Net::OpenID::Consumer:         0.12
    Net::Yadis::Discovery:         0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
